export SGL_DISABLE_TP_MEMORY_INBALANCE_CHECK=True

DATA_DIR=${DATA_DIR:-./data}
MODEL_PATH=${MODEL_PATH:-/path/to/latent-sft-checkpoint/hf}
OUTPUT_DIR=${OUTPUT_DIR:-./saved/latent-grpo-math500-qwen}
GPUS=${GPUS:-0,1,2,3,4,5,6,7}

PYTHONUNBUFFERED=1 CUDA_LAUNCH_BLOCKING=1 HYDRA_FULL_ERROR=1 CUDA_VISIBLE_DEVICES=${GPUS} python3 -m verl.trainer.main_ppo \
algorithm.adv_estimator=grpo \
data.train_files=${DATA_DIR}/DAPO-Math-17k-en-train.parquet \
data.val_files=${DATA_DIR}/Math-500-test.parquet \
data.train_batch_size=32 \
data.val_batch_size=500 \
data.max_prompt_length=1024 \
data.max_response_length=4096 \
data.filter_overlong_prompts=True \
actor_rollout_ref.model.path=${MODEL_PATH} \
actor_rollout_ref.actor.optim.lr=1e-6 \
actor_rollout_ref.model.use_remove_padding=True \
actor_rollout_ref.actor.ppo_mini_batch_size=32 \
actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
actor_rollout_ref.actor.use_kl_loss=True \
actor_rollout_ref.actor.ppo_max_token_len_per_gpu=20480 \
actor_rollout_ref.actor.kl_loss_coef=0.001 \
actor_rollout_ref.actor.neg_adv_weight=1.0 \
actor_rollout_ref.actor.kl_loss_type=low_var_kl \
actor_rollout_ref.actor.entropy_coeff=0 \
actor_rollout_ref.actor.freeze_embedding=True \
actor_rollout_ref.model.enable_gradient_checkpointing=True \
actor_rollout_ref.actor.fsdp_config.param_offload=True \
actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2 \
actor_rollout_ref.rollout.max_model_len=12000 \
actor_rollout_ref.rollout.max_num_batched_tokens=12000 \
actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
actor_rollout_ref.rollout.name=sglang \
actor_rollout_ref.rollout.dtype=bfloat16 \
actor_rollout_ref.rollout.top_p=0.95 \
actor_rollout_ref.rollout.top_k=30 \
actor_rollout_ref.rollout.max_topk=10 \
actor_rollout_ref.rollout.temperature=0.6 \
actor_rollout_ref.rollout.gumbel_softmax_temperature=1.0 \
actor_rollout_ref.rollout.enable_latent=True \
actor_rollout_ref.rollout.latent_end_token_id=522 \
actor_rollout_ref.rollout.add_noise_gumbel_softmax=True \
actor_rollout_ref.rollout.use_one_sided_gumbel_noise=True \
actor_rollout_ref.rollout.noise_scale=1.0 \
actor_rollout_ref.rollout.val_kwargs.do_sample=True \
actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
actor_rollout_ref.rollout.val_kwargs.top_k=30 \
actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
actor_rollout_ref.rollout.n=8 \
actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2 \
actor_rollout_ref.ref.strategy=fsdp2 \
algorithm.use_kl_in_reward=False \
algorithm.exclude_overlong_samples_from_advantage=True \
algorithm.filter_groups.enable=True \
algorithm.filter_groups.max_num_gen_batches=50 \
trainer.critic_warmup=0 \
trainer.logger=['console','wandb'] \
trainer.project_name='latent-grpo' \
trainer.experiment_name='latent-grpo-math500-qwen' \
trainer.val_before_train=True \
trainer.n_gpus_per_node=8 \
trainer.nnodes=1 \
trainer.save_freq=40 \
trainer.test_freq=10 \
trainer.default_hdfs_dir=null \
trainer.balance_batch=True \
trainer.default_local_dir=${OUTPUT_DIR} \
trainer.total_epochs=5

